### ISSUE TITLE
Generalize vx/vy to other properties

### ISSUE THREAD

**Issue by ddurschlag** [d3/d3-force#102]
It would be useful to be able to have other properties (like x/y) and their derivatives (like vx/vy) modeled, allowing for (e.g.) color, size, or other visual properties of a node to be affected by the simulation. Obviously, these could not be "first class" citizens like x and y, since they wouldn't be involved in distance calculation, quad-tree construction, etc., though they could be affected by such calculations.

**Comment by mbostock** [comment]
You’re welcome to implement forces that set other properties on nodes, but my strategy for this module is to limit d3.forceSimulation to 2D velocity Verlet to keep things simple. See https://github.com/d3/d3-force/pull/90#issuecomment-289616180 for a bit of context; see also [d3-force-3d](https://github.com/vasturiano/d3-force-3d).
