### ISSUE TITLE
doc: forceLink seems to replace string IDs with links to objects, but this is not documented

### ISSUE THREAD

**Issue by safinaskar** [d3/d3-force#103]
forceLink seems to replace string IDs with links to objects, but this is not documented. I. e. https://github.com/d3/d3-force/blob/master/README.md#forceLink doesn't say anything about this. I discovered this only by experimenting with code

**Comment by mbostock** [comment]
It’s implied in two places, but I agree it should be clearer. In *link*.links:

> Each link is an object with the following properties:
>
> * *source* - the link’s source node; see *simulation*.nodes
> * *target* - the link’s target node; see *simulation*.nodes
> * *index* - the zero-based index into *links*, assigned by this method
>
> For convenience, a link’s source and target properties may be initialized using numeric or string identifiers rather than object references; see *link*.id.

And in *link*.id:

> The id accessor is invoked for each node whenever the force is initialized, as when the nodes or links change, being passed the node and its zero-based index.

So the implication is that if you don’t specify *link* objects whose *link*.source and *link*.target properties are objects, they will be replaced by object references whenever the link force is initialized. See the implementation here:

https://github.com/d3/d3-force/blob/c7d165a72e2ebd74e5dda43e176d9326c7d424e8/src/link.js#L60-L61

This applies not just to string identifiers but the default numeric indexes, too (when you haven’t specified a custom *link*.id accessor).

Forces are initialized when they are attached to simulations and when the simulation’s nodes change. Related, [*simulation*.force](https://github.com/d3/d3-force/blob/master/README.md#simulation_force) and [*simulation*.nodes](https://github.com/d3/d3-force/blob/master/README.md#simulation_nodes) should explicitly mention that they (re-)initialize forces; this is currently only documented by [*force*.initialize](https://github.com/d3/d3-force/blob/master/README.md#force_initialize).
