### ISSUE TITLE
'd3-force' does not contain an export named 'forceRadial'

### ISSUE THREAD

**Issue by resson-ntranquilla** [d3/d3-force#105]
- version in package.json: ^1.0.6. yarn shows it resolves to https://registry.yarnpkg.com/d3-force/-/d3-force-1.0.6.tgz#ea7e1b7730e2664cd314f594d6718c57cc132b79
- Steps to reproduce
    - `import { forceRadial } from "d3-force" `
    - attempt to execute function 'forceRadial', and get error: 'd3-force' does not contain an export named 'forceRadial'
- No such error when importing forceCollide

**Comment by mbostock** [comment]
It hasn’t been released yet.

**Comment by mbostock** [comment]
Released in 1.1.0.
