### ISSUE TITLE
Breaking change to d3.forceSimulation in Version 4.12.1

### ISSUE THREAD

**Issue by MauriceBrg** [d3/d3-force#109]
Hey!

I'm new to the d3 library and might have discovered a bug with the forceSimulation in the latest version.

For me some of the examples aren't working with the latest Version of d3 js.

Here is a list of them:

- https://bl.ocks.org/mbostock/4600693
- https://bl.ocks.org/HarryStevens/bc938c8d45008d99faed47039fbe5d49
- https://bl.ocks.org/mbostock/aba1a8d1a484f5c5f294eebd353842da

I tested these with the following Browsers:
Firefox 57.0.2
Google Chrome 63

They seem use the d3 version from https://d3js.org/d3.v4.min.js which currently is 4.12.1. Using that source produces the following error:

> Uncaught TypeError: Cannot read property 'force' of undefined at (index):28

The issue seems to be with function calls like these:

`d3.forceSimulation().force(...)`

When I use version 4.12.0 from https://cdnjs.cloudflare.com/ajax/libs/d3/4.12.0/d3.min.js everything runs smoothly.

Unfortunately I don't (yet) have sufficient knowledge of the library to narrow it down further, but something broke between version 4.12.0 to 4.12.1.

**Comment by mbostock** [comment]
This appears to be a bug in UglifyJS, which was updated in the 4.12.1 release. It is rewriting the return statement of d3.forceSimulation and dropping the assignment to `simulation = `.

**Comment by MauriceBrg** [comment]
Okay - is downgrading that library an option or do we have to wait for them to fix the issues?

**Comment by mbostock** [comment]
Filed as mishoo/UglifyJS2#2666. I have pushed 4.12.2 which reverts to an earlier version of UglifyJS.
