### ISSUE TITLE
link strength function should have access to the count object

### ISSUE THREAD

**Issue by alexlenail** [d3/d3-force#128]
The default link strength function uses an object called `count` to make the attractive strength between two nodes connected by an edge inversely proportional to the degrees of those nodes. 

https://github.com/d3/d3-force/blob/00268ddf6a85be7fa21795e8fca06b76ac612bac/src/link.js#L27-L29

There's the option to [set the strength of the force on the links](https://github.com/d3/d3-force/blob/master/README.md#link_strength), such that we might be able to [change it on the fly](https://bl.ocks.org/mbostock/aba1a8d1a484f5c5f294eebd353842da). This function is supplied the link, the index, and the array of links: 

https://github.com/d3/d3-force/blob/00268ddf6a85be7fa21795e8fca06b76ac612bac/src/link.js#L77

But not the `count` object. So if I wanted to set the strength as some scalar multiple of the default formula, I need to recompute counts, which is a shame. 

Would it be reasonable to pass the counts object across to the link strength callback?

**Comment by Fil** [comment]
This would probably also apply to *link*.distance() as well?
https://github.com/d3/d3-force#link_distance

**Comment by Fil** [comment]
I'm closing this in order to keep the API simple. The *count* object is just a private optimization of the function given in the documentation.
