### ISSUE TITLE
Currently shipping ES6 syntax

### ISSUE THREAD

**Issue by aendrew** [d3/d3-force#134]
At the moment, d3-force is shipping ES6 syntax as per [here](https://github.com/d3/d3-force/blob/master/src/link.js#L54). 

Because d3-force isn't transpiled, this is breaking IE11 and other older browsers.

As per [this comment on d3-geo-projection](https://github.com/d3/d3-geo-projection/issues/158#issuecomment-454482807), this doesn't seem intentional, at least presently.

**Comment by mbostock** [comment]
This is intentional and the reason why [2.0](https://github.com/d3/d3-force/releases/tag/v2.0.0) was a major version bump. If you don’t want modern syntax, please don’t upgrade to 2.0 and stick with 1.x.

**Comment by aendrew** [comment]
Ah, fair enough! Thanks for the explanation!
