### ISSUE TITLE
not support IE

### ISSUE THREAD

**Issue by lxfu** [d3/d3-force#150]
Link.js used the arrow function on line 56.

let i,
      n = nodes.length,
      m = links.length,
      nodeById = new Map(nodes.map((d, i) => [ id(d, i, nodes), d ])),
      link;

**Comment by mbostock** [comment]
https://github.com/d3/d3-force/releases/tag/v2.0.0

**Comment by jaspreetnabha** [comment]
@mbostock, I am getting same error. I am using amcharts which internally using d3-force ^2.0.1 version. Please let me what version needs to be used ?

**Comment by gordonwoodhull** [comment]
Please look at the above link. 

Clearly you need 1.x

**Comment by jaspreetnabha** [comment]
@gordonwoodhull , The issue is that I am using AMCharts which internally uses D3 and D3-force. I can't refer lower versions of D3. Please advise how can I transpile it or use older version of D3-force.

**Comment by gordonwoodhull** [comment]
AFAIK if amCharts is using d3-force v2 then it is not compatible with IE and there’s no point reporting it here. 

It says on [their compatibility page](https://www.amcharts.com/docs/v4/browser-compatibility/) that their force-directed tree is not compatible with IE. You’d probably have to take it up with them or downgrade your amCharts.
