### ISSUE TITLE
Is there a way to avoid superposition of edges & nodes ?

### ISSUE THREAD

**Issue by redouane59** [d3/d3-force#153]
Hi,

In this example, we could think that there is a link between these two nodes : 
![image](https://user-images.githubusercontent.com/4500524/72548862-ddbf4500-388f-11ea-8377-ffeda5476728.png)
 but in reality they are not connected, the edge is just passing through this node to go to another one.
![image](https://user-images.githubusercontent.com/4500524/72549246-9d13fb80-3890-11ea-9fab-6ff00c9006a7.png)

Is there a way to avoid this behavior please ?

**Comment by mbostock** [comment]
There’s nothing built-in to prevent this, but possibly you could write a custom force that tries to avoid edges passing through unrelated nodes.

**Comment by redouane59** [comment]
Do you have an idea to disable the fact that the edges / the nodes tend to be always aligned with others on the same line provoking this behavior ?

https://twitter-social-graph.firebaseapp.com/index.html
