### ISSUE TITLE
Filtering a force directed graph

### ISSUE THREAD

**Issue by JFLopez7** [d3/d3-force#166]
Hi! 

I'm working on a forced directed graph and I need to make a filter to only show the nodes and links for the data that belongs to a group greater than the number 3, but due to the fact that I'm not an expert with the d3 library, all my efforts have been worthless.

For the sake of an example, here is a plunk with some dummy data that simulates the behaviour of my production graph: https://embed.plnkr.co/plunk/SawtfmR9iZvlLWue

I hope you guys can guide me through a solution for this.

Best regards,

Juan

**Comment by Fil** [comment]
I see you're already filtering the display with a specific opacity `node.style("opacity", function (o) { return neigh(index, o.index) ? 1 : 0.1; });`; this is probably the place to insert the logic you want. The group appears be accessible in o.group.

PS: this is not the best place to ask for help. For questions about D3’s behavior, please consider using the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).
