### ISSUE TITLE
More Tests

### ISSUE THREAD

**Issue by mbostock** [d3/d3-force#17]

**Comment by timruffles** [comment]
What test framework do you use?

**Comment by curran** [comment]
[Tape](https://github.com/substack/tape) is used for all the D3 tests. The [tests in d3-array](https://github.com/d3/d3-array/tree/master/test) are nice examples of how tests are written with Tape. Also, there is already a placeholder for invoking tests in d3-force using the "test" script in [package.json](https://github.com/d3/d3-force/blob/master/package.json).

**Comment by amejiarosario** [comment]
@mbostock I'd like to help with the tests. Are you accepting PR for this?

**Comment by Fil** [comment]
I've started a first batch of tests, but there's a lot of coverage to do.
