### ISSUE TITLE
This line breaks ie supports even if there is babel

### ISSUE THREAD

**Issue by AtahanAltiparmak** [d3/d3-force#181]
https://github.com/d3/d3-force/blob/8c4d113979291aa21a9639263c43aa494a191a94/src/link.js#L55

**Comment by AtahanAltiparmak** [comment]
This line of code should be like below

```
nodeById = new Map(nodes.map(function(d, i) {
    return [id(d, i, nodes), d];
 })),
```

**Comment by mbostock** [comment]
Please find another forum to request help with Babel.

**Comment by Fil** [comment]
There is a working example at https://github.com/Fil/d3-template
Live version https://d3-template.fil.vercel.app/
Tested both with `es-check es5 dist/*js` and with browserstack against IE9.

**Comment by AtahanAltiparmak** [comment]
> There is a working example at https://github.com/Fil/d3-template
> Live version https://d3-template.fil.vercel.app/
> Tested both with `es-check es5 dist/*js` and with browserstack against IE9.

Thank you @Fil . We are developing quasar spa vue application in our company. This library is used in Amcharts as a dependency.  By the way, I solved my problem with the quasar.conf.js like below

`build: {
      transpileDependencies: [
        '@amcharts',
      ],
...
}`
