### ISSUE TITLE
Forcing angle in crystalline structure

### ISSUE THREAD

**Issue by fabiospampinato** [d3/d3-force#197]
Hello there, I'm using d3-force for a little simulation where nodes have labels attached to them visually.

The problem is that if nodes happen to align ~horizontally then those labels are really crammed in there visually:

<img width="849" alt="Screen Shot 2021-06-16 at 15 40 16" src="https://user-images.githubusercontent.com/1812093/122241294-59c12080-ceba-11eb-9357-69f59290d43a.png">

While if nodes are aligned ~vertically labels are laid out much better:

<img width="842" alt="Screen Shot 2021-06-16 at 15 40 27" src="https://user-images.githubusercontent.com/1812093/122241489-7f4e2a00-ceba-11eb-9964-0d453a1c27fd.png">

Those two crystalline (?) structures are both hexagonal, but basically the difference is that if the pointy tips of the hexagon are aligned vertically the thing looks great, while if they are aligned horizontally the thing looks pretty bad.

What would be the best way to force the pointy tips to align vertically? I'm thinking that maybe I should change the collision force, since the default one expects point-like masses, should that work? If so is there some already-done alternative collision force that I could use for this?

**Comment by Fil** [comment]
please open a [discussion](https://github.com/d3/d3/discussions) instead of an issue
