### ISSUE TITLE
simulation compute x/y/vx/vy as NAN sometimes

### ISSUE THREAD

**Issue by fakerName** [d3/d3-force#198]
![image2021-7-15_12-4-15](https://user-images.githubusercontent.com/17928352/125741255-5d505243-3207-4e8c-8778-88f941cc5770.png)
![image2021-7-15_12-5-44](https://user-images.githubusercontent.com/17928352/125741261-bcbdb6ff-9f44-4e01-a8a9-b359bd9bce96.png)
![image2021-7-15_14-29-28](https://user-images.githubusercontent.com/17928352/125741266-483d7b11-ccc7-40d0-a189-78c3b0270594.png)
![image2021-7-15_14-30-19](https://user-images.githubusercontent.com/17928352/125741268-addcba8b-b5e4-44bf-a0bd-7948b1137894.png)

**Comment by Fil** [comment]
please share a minimal reproducible example, we can't work from screenshots
