### ISSUE TITLE
All nodes starts to move when click and holding one node

### ISSUE THREAD

**Issue by 87prashant** [d3/d3-force#209]
I don't know if it is a bug or not. Here is what I meant:

https://user-images.githubusercontent.com/106697681/197469743-1843dc88-2d1c-4ed2-aee9-d25f11f0f10a.mp4

I believe we can fix the other node's position here:

![Screenshot 2022-10-24 011541](https://user-images.githubusercontent.com/106697681/197470439-7ec841f0-c77b-4a9c-b94b-e30967102ffb.png)

But I am not getting why other nodes start to move when we click and hold any one node. How force changes between nodes in this case?

Could someone help me with this?

**Comment by ooodummy** [comment]
It's not a bug it is meant to jiggle.

**Comment by mbostock** [comment]
It’s this line here which reheats the simulation when you start dragging:

```js
      if (!event.active) simulation.alphaTarget(0.3).restart();
```

You need to reheat the graph on interaction or else the nodes won’t respond to the node you move as expected. Of course you’re free to remove this line of code and try it another way.

**Comment by 87prashant** [comment]
Thank you guys for helping!!
