### ISSUE TITLE
Cant pass extra data in nodes in simulation.nodes function

### ISSUE THREAD

**Issue by elVengador** [d3/d3-force#211]
I want to pass extra data like nodeId to use later
For example find a node under mouse cursor, then get nodeId and make some operations

Im building nodes inthis way:
```js
const nodes: (SimulationNodeDatum)[] = notes.map(c => Object.create(c))
```
all extra data from `notes` is removed
if I force like this: 
```js
const nodes: (SimulationNodeDatum)[] = notes.map(c => Object.create({ ...c, tmp: true }))
````
I have an error:
![image](https://user-images.githubusercontent.com/27080940/198504300-2553f6d3-b4fb-4d22-bb08-2814cb96125b.png)

**Comment by Fil** [comment]
It seems to be working here https://observablehq.com/@recifs/simulation-nodes-with-added-data--support
