### ISSUE TITLE
d3 v7 chained methods of forceLink "is not a fucntion"

### ISSUE THREAD

**Issue by staysh** [d3/d3-force#215]
`d3.forceLink().id().strength()` results in an uncaught TypeError that it is not a function

`d3.forceLink().id() //ok`
`d3.forceLink().strength() //ok`

**Comment by Fil** [comment]
works as expected; see https://github.com/d3/d3-force#link_id for details

**Comment by mbostock** [comment]
I think the confusion here is that you can only chain when you pass _link_.id an argument. If you don’t pass an argument, then _link_.id is a getter, returning the current id. So:

```js
const link = d3.forceLink();
console.log(link.id()); // returns the current id accessor
link.id((d) => d.id); // sets the id accessor and returns link
``

So, this is fine:

```js
link.id((d) => d.id).strength(10); // 👍
```

But this is nonsensical because link.id() without an argument returns the current id accessor, not the link force.

```js
link.id().strength(); // 👎
```
