### ISSUE TITLE
Creating a transition before stopping the layout prevents it from restarting

### ISSUE THREAD

**Issue by robinhouston** [d3/d3-force#34]
Creating an unrelated transition before calling `layout.stop()` has the surprising effect that subsequent calls to `layout.restart()` have no effect.

See the test case at https://bl.ocks.org/robinhouston/27dd39ede1186d4a7e3e12c16f482b41: if you press the “Transition & stop” button while the layout is still ticking, then the “Restart” button does not restart it.

It’s possible this is actually a bug in `d3-timer`, since the most obvious connection between layouts and transitions is that both use timers internally.

**Comment by robinhouston** [comment]
I can confirm that, as expected, creating a timer has the same effect as creating a transition and prevents the layout from restarting. See https://bl.ocks.org/robinhouston/39a9f6e05a7b3a0fceca77051a9d1453

**Comment by mbostock** [comment]
Definitely sounds like a d3-timer bug. I squashed a related bug here
recently but it’s possible I missed something. I will investigate after I
have my morning coffee! Thank you for the test case.

**Comment by mbostock** [comment]
Fixed in [d3-timer](https://github.com/d3/d3-timer) [0.5.1](https://github.com/d3/d3-timer/releases/v0.5.1). I’ll push a new D3 bundle, too, shortly.
