### ISSUE TITLE
simulation.fix missing

### ISSUE THREAD

**Issue by crazygodflo** [d3/d3-force#41]
Hi,

I'm including the following : 
<script src="https://d3js.org/d3-collection.v1.min.js"></script>
<script src="https://d3js.org/d3-dispatch.v1.min.js"></script>
<script src="https://d3js.org/d3-quadtree.v1.min.js"></script>
<script src="https://d3js.org/d3-timer.v1.min.js"></script>
<script src="https://d3js.org/d3-force.v1.min.js"></script>

When I try to perform a simulation.fix / unfix, the function is not found.

What am I missing ?

Best

**Comment by mbostock** [comment]
Please read the release notes: https://github.com/d3/d3-force/releases

I have also just now updated several examples using D3 4.0 alpha to use the final D3 4.0 release. Sorry for the confusion.

**Comment by crazygodflo** [comment]
Wow what a reactivity ! Thanks a lot Mike, cheers !
