### ISSUE TITLE
clarifying d3-force documentation

### ISSUE THREAD

**Issue by denjn5** [d3/d3-force#47]
I believe, for clarity the [d3-force documentation] (https://github.com/d3/d3-force/blob/master/README.md#forceSimulation)...
- "mutally" should be "mutually" in the sentence, "The many-body (or n-body) force applies mutally amongst all nodes."
- "number in [0,1]" should be "number in the range [0,1]" (6 instances).

**Comment by mbostock** [comment]
Thanks. In the future, feel free to open a pull request for this sort of thing!

**Comment by denjn5** [comment]
I wondered about that. Thanks for the change. Loving the new features in v4.
