### ISSUE TITLE
Multiple forces like forceX and forceY

### ISSUE THREAD

**Issue by tomgasson** [d3/d3-force#48]
It seems that `forceX` and `forceY` could be implemented as one common function with their difference exported as a usage of a general `axisForce` function
```js
export const forceX = axisForce('x') // or given an accessor fn
export const forceY = axisForce('y')
```
Which would make it simple to create a `forceZ` or similar.

My use case is to take something like [your beeswarm example](http://bl.ocks.org/mbostock/6526445e2b44303eebf21da3b6627320) and pre-solve positions for both a clustered view and a category separated view similar to [your corporate tax rates viz](http://www.nytimes.com/interactive/2013/05/25/sunday-review/corporate-taxes.html?_r=0). The problem I have is that the second force overwrites the first.

I've worked it out by doing this:

```js
  
let data = data.map(d => ( {
  ...d,
  split: { ...d },
  grouped: { ...d }
}))

var grouped = d3.forceSimulation(data.map(d => d.grouped)) // force acts on subobject
  .force("x", d3.forceX(function(d) { return x(d.value); }).strength(1))
  .force("y", d3.forceY(height / 2))
  .force("collide", d3.forceCollide(4))
  .stop();

for (var i = 0; i < 120; ++i) grouped.tick();

var split = d3.forceSimulation(data.map(d => d.split)) // force acts on subobject
  .force("x", d3.forceX(function(d) { return x(d.value); }).strength(1))
  .force("y", d3.forceY(d => categoryScale(d.category)) // different
  .force("collide", d3.forceCollide(4))
  .stop();

for (var i = 0; i < 120; ++i) split.tick();


// usage
function update(grouped){
    circles
      .transition()
      .duration(400)
      .attr("cx", d => d[grouped?'grouped':'split'].x; })
      .attr("cy", d => d[grouped?'grouped':'split'].y; });
}
update(true)
```

Just wondering if there's a better way to achieve this?

**Comment by mbostock** [comment]
The simulation is inherently two-dimensional, not *n*-dimensional. Even if you make an *n*-dimensional (or arbitrary-dimension) force, the simulation and the other forces are specific to *x* and *y*; see the [implementation of tick](https://github.com/d3/d3-force/blob/master/src/simulation.js#L47-L53). So, if you want to compute two different layouts of the same network, I do think it makes the most sense to have two copies of that network and two simulations with different forces.
