### ISSUE TITLE
reproduce v3 simulation under v4

### ISSUE THREAD

**Issue by jo-pol** [d3/d3-force#51]
With v3 I created a an application with more intricate cloth than the [lattice](http://bl.ocks.org/mbostock/1b64ec067fcfc51e7471d944f51f1611) example. I fail to reproduce the behavior of v3 under v4. Under v4 I only manage to inflate or deflate the graphs or create a complete mess. The links no longer behave like rubber bands. The nodes hardly rearrange themselves unless they collide. Demos of the [v3](https://d-bl.github.io/GroundForge/) implementation and [v4](https://jo-pol.github.io/GroundForge/) attempt. The panel below the two D3 diagrams show the initial state of the left diagram. One line in the left diagram represents two lines in the right diagram. Both diagrams are generated with the same script though the links have different representations. Colored end-markers (and occasional mid-markers) in the left diagram. White end markers in the right diagram are implemented by drawing the links slightly shorter.

The configuration of the v3 `d3.layout.force()` are shown above this [code comment](https://github.com/d-bl/GroundForge/pull/61/files#diff-d954fe9b7e3c4b571ef0e2859242bb80R204). Below the message an attempt to configure the v4 `d3.forceSimulation()` and another message pointing to other attempts.

I'm afraid I have too little math background to understand the influence of all the parameters and which I'm missing. Any hints to restore the rubber-band like behavior of the links would be very much appreciated.

**Comment by mbostock** [comment]
Sorry, but that’s too much code for me to debug. If you can create a smaller example that demonstrates an issue, I can take another look, but there could be many reasons why your code isn’t working and it’s too time-consuming for me to debug a large amount of unfamiliar code. 

It’s hard to tell because you’re using the minified version of D3, but it looks like the *nodes* and *links* that you are passing to d3.forceSimulation and d3.forceLink, respectively, are selections rather than data. I think you meant to pass `arg.nodes` and `arg.links` instead.

**Comment by jo-pol** [comment]
I just hoped it would be something obvious.

Pretty ignorant I guess I mixed up data an selection because I got an exception using `args.nodes`  and `args.links` and not with `nodes` and `links`. With a fresher head I now figured out how to [fix](https://github.com/jo-pol/GroundForge/blob/3889b3b73c9994492fc4750aea8d33c48ec411b3/js/show-graph.js#L72-L77) the problems I ran into with [this loop](https://github.com/d3/d3-force/blob/e6ac2336707604826f43da632c8ec8a3a96275e1/src/link.js#L56-L61) in d3.v4.js.

I'll play around again for a while before I collect the courage to create a smaller example.
Thanks for having a look.

**Comment by jo-pol** [comment]
You did spot the problem. I kept mixing things up but finally tackled it. Thanks again.

**Comment by sumit2201** [comment]
How did you manage to do it? I am also struggling to replicate exact force layout in d3 version v4 as I did in version 3 of d3?

**Comment by jo-pol** [comment]
The conversation above explains the essential mistakes I made with the new API. You don't get slapped on your wrist for mistakes so it required some debugging to figure out where I mixed up things.

Then behavior still was a bit different, so I tweaked the parameters until I got something that pleased me more than the original behavior. So no I did not replicate exactly the original force layout.
