### ISSUE TITLE
simulation.size()

### ISSUE THREAD

**Issue by ramijarrar** [d3/d3-force#54]
We used this function to handle window resize in v3 (so the graph shifts into view)

I had a look through the CHANGES document but couldn't find any information relating to why this was removed/how to achieve something similar in v4.

**Comment by mbostock** [comment]
The only effect that the old force layout.size had was to set the attraction point for the "gravity" force to be [width / 2, height / 2]. This has been replaced by the positioning forces d3.forceX and d3.forceY, and you can set the focus coordinates of these forces using x.x and y.y respectively as documented in the README.
