### ISSUE TITLE
manyBody.js: calculate the change of node velocity

### ISSUE THREAD

**Issue by BlackGanglion** [d3/d3-force#56]
```
var x = quad.x - node.x,
    y = quad.y - node.y,
    w = x2 - x1,
    l = x * x + y * y;

if (w * w / theta2 < l) {
  if (l < distanceMax2) {
    if (x === 0) x = jiggle(), l += x * x;
    if (y === 0) y = jiggle(), l += y * y;
    if (l < distanceMin2) l = Math.sqrt(distanceMin2 * l);
    node.vx += x * quad.value * alpha / l;
    node.vy += y * quad.value * alpha / l;
  }
  return true;
}
```

Sorry, I couldn't understand why `l = x * x + y * y` rather than `l =  Math.sqrt(x * x + y * y)`, so I couldn't know the principle of `node.vx += x * quad.value * alpha / l`. Could you explain to me?

**Comment by curran** [comment]
See https://github.com/d3/d3-force/blob/master/src/manyBody.js#L106 :

```js
  force.distanceMax = function(_) {
    return arguments.length ? (distanceMax2 = _ * _, force) : Math.sqrt(distanceMax2);
  };
```

Notice that `distanceMax2 = _ * _`, not `distanceMax2 = _`. 

`l` is being compared to the distance squared (the `2` means squared), which is equivalent to comparing `sqrt(l)` to the distance.

**Comment by curran** [comment]
Also, I believe the principle of comparing to the quad value relates to the [Barnes-Hut Algorithm](https://en.wikipedia.org/wiki/Barnes%E2%80%93Hut_simulation), which approximates forces of many bodies at a distance using an aggregated body based on the quadtree.

**Comment by mbostock** [comment]
The force is inversely proportional to the square of the distance; see [Newton’s theory of gravitation](https://en.wikipedia.org/wiki/Gravity#Newton.27s_theory_of_gravitation).

**Comment by BlackGanglion** [comment]
In my opinion，`node.vx += x * (quad.value / l) * alpha`，`quad.value / l` is the gravitation or electric field force，why `force * x` rather than `force * x / Math.sqrt(l)`?
