### ISSUE TITLE
Accept radius accessor in simulation.find

### ISSUE THREAD

**Issue by ramijarrar** [d3/d3-force#57]
This would enable working with multiple node sizes on the same graph (as we can already do with the collision force)

**Comment by mbostock** [comment]
Thanks for the suggestion. However, I have no plans to add this feature. The [implementation](https://github.com/d3/d3-force/blob/master/src/simulation.js#L116-L137) of [*simulation*.find](https://github.com/d3/d3-force/blob/master/README.md#simulation_find) is super-simple: it’s just a linear scan of the nodes. If you want to make it do something more complicated, I recommend copying the code and changing the implementation as needed.
