### ISSUE TITLE
velocityDecay should be a force

### ISSUE THREAD

**Issue by Fil** [d3/d3-force#75]
If we are seeing d3-force as physics simulations, friction is a force. Thus, it feels inconsistent to have it implemented as a magical `velocityDecay` parameter. (A logical explanation could be that it is much faster this way and most always needed.)

I'm not claiming that it needs to be changed, but it bothers me. Feel free to close this as a rant.

**Comment by mbostock** [comment]
The same could be said of the handling of *node*.fx and *node*.fy to fix positions. But in both cases I think the answer is that these should be applied as the last step of each tick. Arbitrary forces, in contrast, should typically be order-independent, and thus the simulation doesn’t need to expose an explicit mechanism for controlling the order in which forces are applied.
