### ISSUE TITLE
use prototype functions for simulation

### ISSUE THREAD

**Issue by jkristoffer** [d3/d3-force#80]
I find that this may be useful to those who may want to extend `simulation.js`

For my case, I wanted to the `find` function to only return nodes with a certain property. But because the variable `nodes` belongs to the scope of the constructor I cannot simply write the following:

```
let simulation = d3.forceSimulation().nodes(nodes);
simulation.findWithProperty = (x,y,radius,property) =>  {
    ...
    nodes.filter(n => n[property]);    // nodes is undefined
    ...
    /**
    *  I imagined maybe `nodes` could be accessible via `this.nodes` 
    */
}
```

**Comment by mbostock** [comment]
There’s no prototype because the methods are implemented as closures and the private state is not exposed. It could be re-written to use underscored fields instead of closures, but I have no immediate plans to implement this. You can implement your proposed method two ways:

```js
simulation.findWithProperty = (x, y, radius, property) => {
  simulation.nodes().filter(…);
};
```

Or:

```js
function findWithProperty(nodes, x, y, radius, property) {
  nodes.filter(…);
}
```

And then:

```js
findWithProperty(simulation.nodes(), x, y, radius, property);
```
