### ISSUE TITLE
Suggestion: pass an accessor to d3.forceLink

### ISSUE THREAD

**Issue by lgrkvst** [d3/d3-force#86]
Instead of passing an array of links, would it be possible for this function to accept an accessor?

That way it would be pretty straight forward to reuse an existing hierarchic data structure (for instance a d3.stratify tree, or a partition tree), in a force-directed network and simply state that:

```
d3.forceSimulation().force("link", d3.forceLink(function(d) {
   return d.children;
}));
```

**Comment by mbostock** [comment]
The recommended pattern would be to use [*root*.descendants](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_descendants) to compute the nodes and [*root*.links](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_links) to compute the links:

```js
var root = d3.hierarchy(…);

var simulation = d3.forceSimulation(root.descendants())
    .force("charge", d3.forceManyBody())
    .force("link", d3.forceLink(root.links()))
    .force("center", d3.forceCenter());
```

https://bl.ocks.org/mbostock/9a8124ccde3a4e9625bc413b48f14b30

**Comment by lgrkvst** [comment]
Amazing – thanks!
