### ISSUE TITLE
Minimal Force Example

### ISSUE THREAD

**Issue by saivan** [d3/d3-force#87]
Now this might just be an issue with the documentation, but when trying to create my own force. I ran into an issue that seems strange to me:

![image](https://cloud.githubusercontent.com/assets/8543370/23065054/a28f07ae-f567-11e6-8587-04a732bfbc43.png)

If I provide a force function in my scope, why would I be able to see the `nodes`, variable, I tried this with a minimal example [here](http://codepen.io/anon/pen/KaLwEg?editors=0010), and it behaved as I expected, if you check your console `nodes` is not defined.

So perhaps we should update this documentation to include a simpler force, it remains unclear to me how a user would be able to iterate through the nodes in the force.

**Comment by mbostock** [comment]
That example assumes that *nodes* is in scope of the *force* function (i.e., it captures *nodes* via closure).

This is a suitable technique for custom forces that are used only once, but if you want a define a new “reusable” force, you should implement [*force*.initialize](https://github.com/d3/d3-force/blob/master/README.md#force_initialize) to get a reference to the simulation’s nodes, or pass the nodes explicitly to your force (related #72; see [example](https://bl.ocks.org/mbostock/b1f0ee970299756bc12d60aedf53c13b)).

If you want another minimal example of a force implementation, look at the forces provided by this library, such as d3.forceX:

https://github.com/d3/d3-force/blob/master/src/x.js
