### ISSUE TITLE
would be nice to allow 3d layout too

### ISSUE THREAD

**Issue by morandd** [d3/d3-force#92]
There are several other projects and d3 extensions that allow 3d layout. But it would be nice to have this nice & cleanly implemented in the main 3d library.  

For example, this project to build FDL's in AFrame is nice, but had to use d3 plus another layout engine (ngraph): https://github.com/vasturiano/3d-force-graph-vr

**Comment by mbostock** [comment]
See https://github.com/d3/d3-force/pull/90#issuecomment-289616180 for a little bit of context as to why I recommended forking rather than making this library support arbitrary dimensions. (That lead to the creation of https://github.com/vasturiano/d3-force-3d.)
