### ISSUE TITLE
How to update force parameters in v4?

### ISSUE THREAD

**Issue by ccoenen** [d3/d3-force#94]
I am trying to do something like in [this v3 example](http://bl.ocks.org/christophermanning/4208494) in v4: the ability to modify forces dynamically. I would love to be able to modify the forces' parameters later on.

I tried different ways, and _also combination_ of these:

- using `manyBody.strength()` to set different value
- nulling and setting the force to the simulation with `simulation.force('charge', null)` and `simulation.force('charge', manybody)`
- restarting the simulation with `simulation.stop()` and `simulation.restart()`

Apparently none of these are effective. Is there a way to change these values later? Specifically manyBody's strength and distances as well as link's strength. The reason is, that I'm currently playing around with a large data set and I'm trying to find good values for these parameters by experimentation.

**Comment by steveharoz** [comment]
Here is an example where forces are updated dynamically - https://bl.ocks.org/steveharoz/8c3e2524079a8c440df60c1ab72b5d03

Check `function updateForces()` to see how parameters are updated in general.

Note that link strength is a bit weird. First update the link strength. Then set the links to empty (`mylinkforce.links( [] )`). Then set the links back again.

"How to" questions are best asked on stackoverflow.com. Please reserve this space for bugs.

**Comment by ccoenen** [comment]
Thank you for the explanations and the example!

**Comment by mbostock** [comment]
The only thing that is required is to set the desired force parameter. Everything else should happen automatically. However, note that if you have configured the simulation to cool (which is the default behavior), you may need to reheat the simulation to observe the effect of this change.

Here’s a simple example of adjusting the link strength interactively:

https://bl.ocks.org/mbostock/aba1a8d1a484f5c5f294eebd353842da

If this is not the case, please reopen the bug, and include a minimal, verifiable live example that demonstrates the issue.

**Comment by ccoenen** [comment]
I can confirm that alpha and restart are all that's neccessary, even for the link-force. Thanks for both of your examples!
